import type { NextPage } from "next";
import Head from "next/head";
import { Exchanges } from "../components/ExchangesTable/Exchanges";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Coin Gecko exchanges directory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Exchanges />
    </div>
  );
};

export default Home;
